Code cleanup/standardisation
* Add files to .gitignore
* Update copyright years
* Add note to INSTALL about my strict build settings,remove CFLAGS/etc from
  other files
* Templatise .in files more generally,add related macros to configure.ac
* Remove redundant command from autogen.sh
* Distinguish new distro-specific dir from system-specific dir
* Update bugreport addresses,use in footer file where possible to be more DRY
* Add --source to scripts which don't have it
* Standardise syntax, refactor for tidiness, robustness, better error output
* Add more thorough unsetting of vars to keep env clean
* Standardise whitespace (tabs to spaces)
* Sanity-check args
* Remove cleanup() too

diff --git a/src/general/nk_common.sh.in b/src/general/nk_common.sh.in
--- a/src/general/nk_common.sh.in
+++ b/src/general/nk_common.sh.in
@@ -1,19 +1,21 @@
+#!@SHELL@
+
 # nk_common.sh:
 #
 # NB: This aims to be POSIX.1-2008 compliant
 #
 ###########
 #
-# Copyright © 2012, 2013 Rowan Thorpe
+# Copyright © 2012, 2013, 2014 Rowan Thorpe
 #
-# This file is part of NOC-Kit.
+# This file is part of @PACKAGE_NAME@.
 #
-# NOC-Kit is free software: you can redistribute it and/or modify
+# @PACKAGE_NAME@ is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
-# NOC-Kit is distributed in the hope that it will be useful,
+# @PACKAGE_NAME@ is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU Affero General Public License for more details.
@@ -23,57 +25,60 @@
 #
 ###########
 #
-# For bug-reports please email: rowan *at* rowanthorpe _DOT_ com
-# (obviously, fix the address with the appropriate symbols and no spaces).
+# Report bugs to @PACKAGE_BUGREPORT@
 
+if test "x$1" = "x--nk-source"; then
+    cat "$0"
+    exit 0
+fi
 if test -z "$__common_sourced"; then
-	__scriptname="$0"
-	__scriptbasename="${__scriptname##*/}"
-	__scriptdirname="$(readlink -q -e -n "${__scriptname%/*}")"
-	__scriptname="${__scriptdirname}/${__scriptbasename}"
+    __scriptname="$(readlink -q -e -n "$0")"
+    __scriptbasename="$(printf %s "$__scriptname" | sed -n -e '$ { s:^.*/\([^/]*\)$:\1:; p }')"
+    __scriptdirname="$(printf %s "$__scriptname" | sed -e '$ s:/[^/]*$::')"
 
-	PACKAGE_VERSION="@PACKAGE_VERSION@"
-	. "${__root_dir}/nk_logic_ops.sh" || { printf %s\\n "Failed to load nk_logic_ops.sh"; return 1; }
-#	. "${__root_dir}/nk_lists.sh" || { printf %s\\n "Failed to load nk_lists.sh"; return 1; } #TODO
+    PACKAGE_VERSION="@PACKAGE_VERSION@"
+    . "${__root_dir}/nk_logic_ops.sh" || { printf %s\\n "Failed to load nk_logic_ops.sh" >&2; return 1; }
+#    . "${__root_dir}/nk_lists.sh" || { printf %s\\n "Failed to load nk_lists.sh"; return 1; } #TODO
 
-	__usage_footer() {
-		cat <<EOF
+    __usage_footer() {
+        cat <<EOF
+ @PACKAGE_BUGREPORT@
 
- Part of the NOC-Kit package.
+ Part of the @PACKAGE_NAME@ package.
  License AGPLv3+: GNU Affero GPL version 3 or later
  <http://gnu.org/licenses/agpl.html>.
  This is free software: you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.
 EOF
-	}
-	__version() { printf "%s - noc-kit %s\n" "$__scriptbasename" "$PACKAGE_VERSION"; }
-	__usage() { true; } # to override
-	__source() { cat "$0"; }
-	__info() { for i; do printf %s\\n "${__scriptbasename}: $i"; done; }
-	__warn() { __info "$@" >&2; }
-	__die() {
-    	if test "x$1" = "x-u"; then __usage >&2; shift; fi
-		if test "x$1" = "x--"; then	shift; fi
-		if test $# = 0; then
-			__exitval=1
-		else
-			if test $# -gt 1; then
-				__exitval=$1
-				shift
-			else
-				__exitval=1
-			fi
-			printf \\n >&2
-			__warn "$@" "Exiting."
-		fi
-		exit $__exitval
-	}
-	__lambda() {
-	    test $# = 2 || { printf %s\\n "Syntax error in __lambda()" >&2; return 1; }
-	    __lambda_vars="$(printf %s "$1" | tr "," " ")"
-	    __lambda_varsnum="$(printf %s "$__lambda_vars" | wc -w)"
-	    __lambda_cmd="$2"
-	    printf %s \
+    }
+    __version() { printf "%s - noc-kit %s\n" "$__scriptbasename" "$PACKAGE_VERSION"; }
+    __usage() { true; } # to override in each script
+    __source() { cat "$0"; }
+    __info() { for i; do printf %s\\n "${__scriptbasename}: $i"; done; }
+    __warn() { __info "$@" >&2; }
+    __die() {
+        if test "x$1" = "x-u"; then __usage >&2; shift; fi
+        if test "x$1" = "x--"; then shift; fi
+        if test $# = 0; then
+            __exitval=1
+        else
+            if test $# -gt 1; then
+                __exitval=$1
+                shift
+            else
+                __exitval=1
+            fi
+            printf \\n >&2
+            __warn "$@" "Exiting."
+        fi
+        exit $__exitval
+    }
+    __lambda() {
+        test $# = 2 || { printf %s\\n "Syntax error in __lambda()" >&2; return 1; }
+        __lambda_vars="$(printf %s "$1" | tr "," " ")"
+        __lambda_varsnum="$(printf %s "$__lambda_vars" | wc -w)"
+        __lambda_cmd="$2"
+        printf %s \
 '__lambda_func() {
     test $# = "'"$__lambda_varsnum"'" || { printf %s\\n "Syntax error: __lambda() requires '"$__lambda_varsnum"' arguments" >&2; return 1; }
     __lambda_func_vars="'"$__lambda_vars"'"
@@ -91,36 +96,37 @@ EOF
     unset __lambda_func_var
     unset __lambda_func_replacement
     eval "$__lambda_func_cmd"
+    unset __lambda_func_cmd
 }
 unset __lambda_vars
 unset __lambda_varsnum
 unset __lambda_cmd
-__lambda_func'
-	}
-	__map() {
-	    __map_cmd="$1"
-	    shift
-	    if __notempty "$@"; then
-	        for __arg do
-	            eval "$__map_cmd" \""$__arg"\"
-	        done
-			unset __map_cmd
-			unset __arg
-	    fi
-	}
-#	__apply() {} #TODO
-#	__filter() {} #TODO
-#	__reduce() {} #TODO
-	__cleanup() {
-	    __map unset $1
-	    __map "unset -f" $2
-	    __map unalias $3
-	    shift 3
-	    __map "rm -fR" "$@" 2>/dev/null
-	}
+__lambda_func
+unset -f __lambda_func'
+    }
+    __map() {
+        __map_cmd="$1"
+        shift
+        if __notempty "$@"; then
+            for __arg do
+                eval "$__map_cmd" \""$__arg"\"
+            done
+            unset __map_cmd
+            unset __arg
+        fi
+    }
+#    __apply() {} #TODO
+#    __filter() {} #TODO
+#    __reduce() {} #TODO
+    __cleanup() {
+        __map unset $1
+        __map "unset -f" $2
+        shift 2
+        __map "rm -fR" "$@" 2>/dev/null
+    }
 
-	__common_cleanup() {
-		__cleanup \
+    __common_cleanup() {
+        __cleanup \
 "__scriptname \
 __scriptbasename \
 __scriptdirname \
@@ -133,8 +139,7 @@ __info \
 __warn \
 __die \
 __lambda \
-__map"
-"" \
+__map" \
 ""
 ## TODO:
 #__apply \
@@ -153,8 +158,8 @@ __map"
 #__list_slice \
 #__list_reverse \
 #__list_sort
-		unset -f __cleanup
-		unset -f __common_cleanup
-	}
-	__common_sourced=1
+        unset -f __cleanup
+        unset -f __common_cleanup
+    }
+    __common_sourced=1
 fi
diff --git a/src/general/slaughter.sh.in b/src/general/slaughter.sh.in
--- a/src/general/slaughter.sh.in
+++ b/src/general/slaughter.sh.in
@@ -1,19 +1,21 @@
-#! @SHELL@
+#!@SHELL@
 
 # slaughter.sh: see --help option for details
+#
+# NB: This aims to be POSIX.1-2008 compliant
 #
 ###########
 #
 # Copyright © 2012, 2013 Rowan Thorpe
 #
-# This file is part of NOC-Kit.
+# This file is part of @PACKAGE_NAME@.
 #
-# NOC-Kit is free software: you can redistribute it and/or modify
+# @PACKAGE_NAME@ is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
-# NOC-Kit is distributed in the hope that it will be useful,
+# @PACKAGE_NAME@ is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU Affero General Public License for more details.
@@ -23,20 +25,19 @@
 #
 ###########
 #
-# For bug-reports please email: rowan *at* rowanthorpe _DOT_ com
-# (obviously, fix the address with the appropriate symbols and no spaces).
+# Report bugs to @PACKAGE_BUGREPORT@
 
 # Config
 __root_dir="@PKGLIBEXECDIR@"
 . "${__root_dir}/nk_common.sh" || {
-	echo "Failed sourcing nk_common.sh. Stopping.">&2
-	exit 1
+    printf "Failed sourcing nk_common.sh. Stopping.\n" >&2
+    exit 1
 }
 
 # Functions
 __usage() {
-	cat <<EOH
-Usage: $__scriptbasenam [OPTIONS] proc [proc] ...
+    cat <<EOH
+Usage: $__scriptbasename [OPTIONS] proc [proc] ...
 
 Try to "kill" a process gently, then not-so-gently, if necessary.
 
@@ -49,22 +50,24 @@ Try to "kill" a process gently, then not-so-gently, if necessary.
  * If invoked as slaughterall (e.g. via symlink) acts analogously to killall
    vs. kill.
 
+ * The --source option does not automatically show sourced libs. To see those
+   execute them directly with one argument: --nk-source
+
 OPTIONS:
  --help|-h|--usage    : This help page.
  --version|-V|--about : Output information about this command.
  --source|-S          : Output this command as source code.
+ --quiet|-q           : Don't output progress.
  --duration|-d        : Sleep duration between kill invocations.
- --repetitions|-r     : How many times to try try -15 before -9.
+ --repetitions|-r     : How many times to try -15 before -9.
  --pattern|-p         : TODO: Explicitly set pattern of signals.
                         Overrides -r and -d. Follows 'sig,dur,...'
                         format (e.g. -p '15,1,15,2,15,2,9,1')
- --quiet|-q           : Don't output progress.
  --                   : End option processing.
 
- Copyright © 2012, 2013 Rowan Thorpe.
- Report bugs to rowan *at* rowanthorpe _DOT_ com
+ Copyright © 2012, 2013, 2014 Rowan Thorpe.
 EOH
-	__usage_footer
+    __usage_footer
 }
 
 # Getopts
@@ -72,57 +75,51 @@ __duration=1
 __repetitions=3
 __verbose=1
 while test -n "$1"; do
-	case "$1" in
-	--help|-h|--usage)
-		__usage
-		exit 0
-		;;
-	--version|-V|--about)
-		__version
-		exit 0
-		;;
-	--source|-S)
-		__source
-		exit 0
-		;;
-	--duration|-d)
-		if test -z "$2" || printf "$2" | grep -q '[^0-9]' || test $2 -gt 255 || test $2 -lt 1; then
-			__die -u "Invalid argument given for: duration."
-		fi
-		__duration="$2"
-		shift 2
-		continue
-		;;
-	--repetitions|-r)
-		if test -z "$2" || printf "$2" | grep -q '[^0-9]' || test $2 -gt 255 || test $2 -lt 1; then
-			__die -u "Invalid argument given for: repetitions."
-		fi
-		__repetitions="$2"
-		shift 2
-		continue
-		;;
-#	--pattern|-p)
-#		TODO: Explicitly set pattern of signals.
-#		      Overrides -r and -d. Follows 'sig,dur,...'
-#		      format (e.g. -p '15,1,15,2,15,2,9,1')
-#		;;
-	--quiet|-q)
-		__verbose=0
-		shift
-		continue
-		;;
-	--)
-		shift
-		break
-		;;
-	-*)
-		__die -u "Unrecognised option specified."
-		;;
-	*)
-		break
-		;;
-	esac
+    case "$1" in
+    --help|-h|--usage)
+        __usage
+        exit 0;;
+    --version|-V|--about)
+        __version
+        exit 0;;
+    --source|-S)
+        __source
+        exit 0;;
+    --quiet|-q)
+        __verbose=0
+        shift
+        continue;;
+    --duration|-d)
+        if test -z "$2" || printf "$2" | grep -q '[^0-9]' || test $2 -gt 255 || test $2 -lt 1; then
+            __die -u "Invalid argument given for \"duration\" option."
+        fi
+        __duration="$2"
+        shift 2
+        continue;;
+    --repetitions|-r)
+        if test -z "$2" || printf "$2" | grep -q '[^0-9]' || test $2 -gt 255 || test $2 -lt 1; then
+            __die -u "Invalid argument given for \"repetitions\" option."
+        fi
+        __repetitions="$2"
+        shift 2
+        continue;;
+#    --pattern|-p)
+#        TODO: Explicitly set pattern of signals.
+#              Overrides -r and -d. Follows 'sig,dur,...'
+#              format (e.g. -p '15,1,15,2,15,2,9,1')
+#        ;;
+    --)
+        shift
+        break;;
+    -*)
+        __die -u "Unrecognised option "$1" specified.";;
+    *)
+        break;;
+    esac
 done
+if test $# -lt 1; then
+    __die -u "Specify at least one argument.'
+fi
 
 # Setup
 __ret=0
@@ -130,52 +127,41 @@ __exit_val=0
 __count=0
 case "$__scriptbasename" in
 slaughter|slaughter.sh)
-	__kill_cmd() {
-		kill -s "$@"
-	}
-	__check_cmd() {
-		ps -p "$@"
-	}
-	__id_type=procid
-	;;
+    __kill_cmd() { kill -s "$@"; }
+    __check_cmd() { ps -p "$@"; }
+    __id_type=procid;;
 slaughterall|slaughterall.sh)
-	__kill_cmd() {
-		killall -s "$@"
-	}
-	__check_cmd() {
-		pgrep -c "^${@}\$"
-	}
-	__id_type=procname
-	;;
+    __kill_cmd() { killall -s "$@"; }
+    __check_cmd() { pgrep -c "^${@}\$"; }
+    __id_type=procname;;
 *)
-	__die -u "Command form $__scriptbasename unknown"
-	;;
+    __die -u "Command form \"$__scriptbasename\" unknown.";;
 esac
 
 # Main
 for __arg in "$@"; do
-	__check_cmd "$__arg" >/dev/null 2>&1 || {
-		__warn "$__id_type $__arg doesn't exist"
-		__exitval=1
-		continue 1
-	}
-	while test $__count -lt $__repetitions; do
-		__kill_cmd 15 "$__arg" >/dev/null 2>&1
-		sleep $__duration
-		__check_cmd "$__arg" >/dev/null 2>&1 || {
-			__warn "Succeeded: __kill_cmd 15 \"$__arg\""
-			continue 2
-		}
-		__warn "Failed: __kill_cmd 15 \"$__arg\""
-		__count=$(( __count+1 ))
-	done
-	__kill_cmd 9 "$__arg" >/dev/null 2>&1
-	sleep $__duration
-	if __check_cmd "$__arg" >/dev/null 2>&1; then
-		__die "Failed: __kill_cmd 9 \"$__arg\""
-		__exitval=1
-	else
-		__warn "Succeeded: __kill_cmd 9 \"$__arg\""
-	fi
+    __check_cmd "$__arg" >/dev/null 2>&1 || {
+        __warn "$__id_type \"$__arg\" doesn't exist."
+        __exitval=1
+        continue 1
+    }
+    while test $__count -lt $__repetitions; do
+        __kill_cmd 15 "$__arg" >/dev/null 2>&1
+        sleep $__duration
+        __check_cmd "$__arg" >/dev/null 2>&1 || {
+            __warn "Succeeded: __kill_cmd 15 \"$__arg\"."
+            continue 2
+        }
+        __warn "Failed: __kill_cmd 15 \"$__arg\"."
+        __count=`eval __count + 1 `
+    done
+    __kill_cmd 9 "$__arg" >/dev/null 2>&1
+    sleep $__duration
+    if __check_cmd "$__arg" >/dev/null 2>&1; then
+        __die "Failed: __kill_cmd 9 \"$__arg\"."
+        __exitval=1
+    else
+        __warn "Succeeded: __kill_cmd 9 \"$__arg\"."
+    fi
 done
 exit $__exitval
