Various tidy-ups and fix the build-process

diff --git a/src/general/nk_common.sh.in b/src/general/nk_common.sh.in
--- a/src/general/nk_common.sh.in
+++ b/src/general/nk_common.sh.in
@@ -1,4 +1,4 @@
-# nk_utils.sh:
+# nk_common.sh:
 #
 # NB: This aims to be POSIX.1-2008 compliant
 #
@@ -26,26 +26,29 @@
 # For bug-reports please email: rowan *at* rowanthorpe _DOT_ com
 # (obviously, fix the address with the appropriate symbols and no spaces).
 
-if test -z "$__utils_sourced"; then
-	__scriptname="$(readlink -q -e -n "$0")"
+if test -z "$__common_sourced"; then
+	__scriptname="$0"
 	__scriptbasename="${__scriptname##*/}"
-	__scriptdirname="${__scriptname%/*}"
+	__scriptdirname="$(readlink -q -e -n "${__scriptname%/*}")"
+	__scriptname="${__scriptdirname}/${__scriptbasename}"
 
-	. "${__root_dir}/nk_tests.sh" || { printf %s\\n "Failed to load nk_tests.sh"; exit 1; }
-#	. "${__root_dir}/nk_lists.sh" || { printf %s\\n "Failed to load nk_lists.sh"; exit 1; } #TODO
+	PACKAGE_VERSION="@PACKAGE_VERSION@"
+	. "${__root_dir}/nk_logic_ops.sh" || { printf %s\\n "Failed to load nk_logic_ops.sh"; return 1; }
+#	. "${__root_dir}/nk_lists.sh" || { printf %s\\n "Failed to load nk_lists.sh"; return 1; } #TODO
 
 	__usage_footer() {
-		cat <<EOH
+		cat <<EOF
 
  Part of the NOC-Kit package.
  License AGPLv3+: GNU Affero GPL version 3 or later
  <http://gnu.org/licenses/agpl.html>.
  This is free software: you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.
-EOH
+EOF
 	}
-	__version() { printf "%s %s - noc-kit %s\n" "$__scriptbasename" "$VERSION" "$NOC_KIT_VERSION"; }
+	__version() { printf "%s - noc-kit %s\n" "$__scriptbasename" "$PACKAGE_VERSION"; }
 	__usage() { true; } # to override
+	__source() { cat "$0"; }
 	__info() { for i; do printf %s\\n "${__scriptbasename}: $i"; done; }
 	__warn() { __info "$@" >&2; }
 	__die() {
@@ -105,6 +108,7 @@ __lambda_func'
 			unset __arg
 	    fi
 	}
+#	__apply() {} #TODO
 #	__filter() {} #TODO
 #	__reduce() {} #TODO
 	__cleanup() {
@@ -115,39 +119,42 @@ __lambda_func'
 	    __map "rm -fR" "$@" 2>/dev/null
 	}
 
-	__utils_cleanup() {
+	__common_cleanup() {
 		__cleanup \
-"" \
 "__scriptname \
 __scriptbasename \
-__scriptdirname" \
-__usage_footer \
-__version \
+__scriptdirname \
+PACKAGE_VERSION" \
+"__usage_footer \
 __usage \
+__version \
+__source \
 __info \
 __warn \
 __die \
-__filter \
-__reduce \
-__list_create \
-__list_destroy \
-__list_append \
-__list_prepend \
-__list_insert \
-__list_pop \
-__list_shift \
-__list_splice \
-__list_length \
-__list_iterate \
-__list_slice \
-__list_reverse \
-__list_sort \
 __lambda \
-__map
+__map"
 "" \
 ""
+## TODO:
+#__apply \
+#__filter \
+#__reduce \
+#__list_create \
+#__list_destroy \
+#__list_append \
+#__list_prepend \
+#__list_insert \
+#__list_pop \
+#__list_shift \
+#__list_splice \
+#__list_length \
+#__list_iterate \
+#__list_slice \
+#__list_reverse \
+#__list_sort
 		unset -f __cleanup
-		unset -f __utils_cleanup
+		unset -f __common_cleanup
 	}
-	__utils_sourced=1
+	__common_sourced=1
 fi
diff --git a/src/general/slaughter.sh.in b/src/general/slaughter.sh.in
--- a/src/general/slaughter.sh.in
+++ b/src/general/slaughter.sh.in
@@ -1,4 +1,4 @@
-#!/bin/sh
+#! @SHELL@
 
 # slaughter.sh: see --help option for details
 #
@@ -27,26 +27,27 @@
 # (obviously, fix the address with the appropriate symbols and no spaces).
 
 # Config
-__prefix=/usr/local
-__root_dir=${__prefix}/libexec/noc-kit
-VERSION=0.2.0
-. "${__root_dir}/nk_utils.sh" || {
-	echo "Failed sourcing nk_utils.sh. Stopping.">&2
+__root_dir="@PKGLIBEXECDIR@"
+. "${__root_dir}/nk_common.sh" || {
+	echo "Failed sourcing nk_common.sh. Stopping.">&2
 	exit 1
 }
 
 # Functions
 __usage() {
 	cat <<EOH
-Usage: slaughter.sh [OPTIONS] procnum [procnum] ...
-       slaughterall.sh [OPTIONS] procname [procname] ...
+Usage: $__scriptbasenam [OPTIONS] proc [proc] ...
 
 Try to "kill" a process gently, then not-so-gently, if necessary.
+
  * By default does "kill -s 15" three times with a sleep 1, then
    "kill -9" with a sleep 1.
- * For slaughterall.sh each arg the command name (without options, etc)
- * if invoked as slaughterall (e.g. via symlink) acts analogously
-   to killall vs. kill.
+
+ * For slaughter.sh each arg is the procnum, for slaughterall.sh each arg is
+   the command name (without its invocation options or parameters)
+
+ * If invoked as slaughterall (e.g. via symlink) acts analogously to killall
+   vs. kill.
 
 OPTIONS:
  --help|-h|--usage    : This help page.
@@ -70,7 +71,7 @@ EOH
 __duration=1
 __repetitions=3
 __verbose=1
-while [ -n "$1" ]; do
+while test -n "$1"; do
 	case "$1" in
 	--help|-h|--usage)
 		__usage
@@ -81,11 +82,11 @@ while [ -n "$1" ]; do
 		exit 0
 		;;
 	--source|-S)
-		cat "$0"
+		__source
 		exit 0
 		;;
 	--duration|-d)
-		if [ -z "$2" ] || printf "$2" | grep -q '[^0-9]' || [ $2 -gt 255 ] || [ $2 -lt 1 ]; then
+		if test -z "$2" || printf "$2" | grep -q '[^0-9]' || test $2 -gt 255 || test $2 -lt 1; then
 			__die -u "Invalid argument given for: duration."
 		fi
 		__duration="$2"
@@ -93,7 +94,7 @@ while [ -n "$1" ]; do
 		continue
 		;;
 	--repetitions|-r)
-		if [ -z "$2" ] || printf "$2" | grep -q '[^0-9]' || [ $2 -gt 255 ] || [ $2 -lt 1 ]; then
+		if test -z "$2" || printf "$2" | grep -q '[^0-9]' || test $2 -gt 255 || test $2 -lt 1; then
 			__die -u "Invalid argument given for: repetitions."
 		fi
 		__repetitions="$2"
@@ -127,7 +128,7 @@ done
 __ret=0
 __exit_val=0
 __count=0
-case "$__exec_name" in
+case "$__scriptbasename" in
 slaughter|slaughter.sh)
 	__kill_cmd() {
 		kill -s "$@"
@@ -147,7 +148,7 @@ slaughterall|slaughterall.sh)
 	__id_type=procname
 	;;
 *)
-	__die -u "Command form $__exec_name unknown"
+	__die -u "Command form $__scriptbasename unknown"
 	;;
 esac
 
@@ -158,7 +159,7 @@ for __arg in "$@"; do
 		__exitval=1
 		continue 1
 	}
-	while [ $__count -lt $__repetitions ]; do
+	while test $__count -lt $__repetitions; do
 		__kill_cmd 15 "$__arg" >/dev/null 2>&1
 		sleep $__duration
 		__check_cmd "$__arg" >/dev/null 2>&1 || {
diff --git a/src/system-specific/zfd.sh.in b/src/system-specific/zfd.sh.in
--- a/src/system-specific/zfd.sh.in
+++ b/src/system-specific/zfd.sh.in
@@ -1,4 +1,4 @@
-#!/bin/sh
+#! @SHELL@
 
 # zfd.sh: see --help option for details
 #
@@ -27,22 +27,26 @@
 # (obviously, fix the address with the appropriate symbols and no spaces).
 
 # Config
-__prefix=/usr/local
-__root_dir=${__prefix}/libexec/noc-kit
-VERSION=0.2.0
-. "${__root_dir}/nk_utils.sh" || {
-	echo "Failed sourcing nk_utils.sh. Stopping.">&2
+__root_dir="@PKGLIBEXECDIR@"
+. "${__root_dir}/nk_common.sh" || {
+	echo "Failed sourcing nk_common.sh. Stopping.">&2
 	exit 1
 }
 
 __usage() {
 	cat <<EOH
-Usage: $__scriptbasename "block_device" "device_nickname" [datetime]
+Usage: $__scriptbasename [OPTIONS] "block_device" "device_nickname" [datetime]
 
 POSIX shell script to quickly zero-out good sectors (only) on a failing disk.
 
   * specify datetime to resume previous invocation of that instance
     (format: %Y_%m_%d-%H_%M_%S)
+
+OPTIONS:
+ --help|-h|--usage    : This help page.
+ --version|-V|--about : Output information about this command.
+ --source|-S          : Output this command as source code.
+ --                   : End option processing.
 
 DESCRIPTION:
 
@@ -74,10 +78,13 @@ TODO:
  * Use blktool, hdparm, raw devices, etc to avoid readahead confusing things
    (for people which --direct doesn't work for?).
 
- * Allow more fine-tuned handling of permissions, rather than just running the
-   whole script as root.
+ * Allow more fine-tuned handling of permissions, rather than just requiring
+   running the whole script as root.
 
+ Copyright © 2012, 2013 Rowan Thorpe.
+ Report bugs to rowan *at* rowanthorpe _DOT_ com
 EOH
+	__usage_footer
 }
 setup() {
 	test "`id -u`" = 0 || __die -u "Must be run as root"
@@ -173,9 +180,24 @@ zero_fill() {
 
 while test -n "$1"; do
 	case "$1" in
-	--help|--usage|-h) usage; exit 0;;
-	--version|-V) __version;;
+	--help|-h|--usage)
+		__usage
+		exit 0
+		;;
+	--version|-V|--about)
+		__version
+		exit 0
+		;;
+	--source|-S)
+		__source
+		exit 0
+		;;
+	--)
+		shift
+		break
+		;;
 	esac
+done
 setup "$@"
 ddrescue_pkg "install"
 for phase_type in fast splitting retrying; do
